//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets95432F1859EBA3693C93F39837B6305B2482685A15D106FA83939EDCF33E6AE2))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets95432F1859EBA3693C93F39837B6305B2482685A15D106FA83939EDCF33E6AE2 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets95432F1859EBA3693C93F39837B6305B2482685A15D106FA83939EDCF33E6AE2()
        {
            this.EdmEntityContainerName = "MobilniPortalNovicContext12";
            this.StoreEntityContainerName = "CodeFirstDatabase";
            this.HashOverMappingClosure = "ec54e049a6628afdbbe67156838e9e999a15ddaeb34cbb78966623041887796b";
            this.HashOverAllExtentViews = "4f76556f3bc0d809c0f932bd920894b23a03e1ea08bb6de01e932ee4ca02cd05";
            this.ViewCount = 12;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.NewsSite
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.NewsSite", @"
    SELECT VALUE -- Constructing NewsSite
        [CodeFirstDatabaseSchema.NewsSite](T1.NewsSite_SiteId, T1.NewsSite_Name)
    FROM (
        SELECT 
            T.SiteId AS NewsSite_SiteId, 
            T.Name AS NewsSite_Name, 
            True AS _from0
        FROM MobilniPortalNovicContext12.NewsSites AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Feed
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Feed", @"
    SELECT VALUE -- Constructing Feed
        [CodeFirstDatabaseSchema.Feed](T1.Feed_FeedId, T1.Feed_url, T1.Feed_CategoryId, T1.Feed_NewsSiteId, T1.Feed_LastUpdated)
    FROM (
        SELECT 
            T.FeedId AS Feed_FeedId, 
            T.url AS Feed_url, 
            T.CategoryId AS Feed_CategoryId, 
            T.NewsSiteId AS Feed_NewsSiteId, 
            T.LastUpdated AS Feed_LastUpdated, 
            True AS _from0
        FROM MobilniPortalNovicContext12.Feeds AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Category
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Category", @"
    SELECT VALUE -- Constructing Category
        [CodeFirstDatabaseSchema.Category](T1.Category_CategoryId, T1.Category_Name)
    FROM (
        SELECT 
            T.CategoryId AS Category_CategoryId, 
            T.Name AS Category_Name, 
            True AS _from0
        FROM MobilniPortalNovicContext12.Categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.NewsFile
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.NewsFile", @"
    SELECT VALUE -- Constructing NewsFile
        [CodeFirstDatabaseSchema.NewsFile](T1.NewsFile_NewsId, T1.NewsFile_ShortContent, T1.NewsFile_Title, T1.NewsFile_Content, T1.NewsFile_PubDate, T1.NewsFile_FeedId)
    FROM (
        SELECT 
            T.NewsId AS NewsFile_NewsId, 
            T.ShortContent AS NewsFile_ShortContent, 
            T.Title AS NewsFile_Title, 
            T.Content AS NewsFile_Content, 
            T.PubDate AS NewsFile_PubDate, 
            T.FeedId AS NewsFile_FeedId, 
            True AS _from0
        FROM MobilniPortalNovicContext12.NewsFiles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.ClickCounter
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.ClickCounter", @"
    SELECT VALUE -- Constructing ClickCounter
        [CodeFirstDatabaseSchema.ClickCounter](T1.ClickCounter_ClickId, T1.ClickCounter_ClickDate, T1.ClickCounter_Location, T1.ClickCounter_NewsId, T1.ClickCounter_UserId)
    FROM (
        SELECT 
            T.ClickId AS ClickCounter_ClickId, 
            T.ClickDate AS ClickCounter_ClickDate, 
            T.Location AS ClickCounter_Location, 
            T.NewsId AS ClickCounter_NewsId, 
            T.UserId AS ClickCounter_UserId, 
            True AS _from0
        FROM MobilniPortalNovicContext12.Clicks AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.User
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.User", @"
    SELECT VALUE -- Constructing User
        [CodeFirstDatabaseSchema.User](T1.User_UserId, T1.User_Username)
    FROM (
        SELECT 
            T.UserId AS User_UserId, 
            T.Username AS User_Username, 
            True AS _from0
        FROM MobilniPortalNovicContext12.Users AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for MobilniPortalNovicContext12.NewsSites
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("MobilniPortalNovicContext12.NewsSites", @"
    SELECT VALUE -- Constructing NewsSites
        [MobilniPortalNovicLib.Models.NewsSite](T1.NewsSite_SiteId, T1.NewsSite_Name)
    FROM (
        SELECT 
            T.SiteId AS NewsSite_SiteId, 
            T.Name AS NewsSite_Name, 
            True AS _from0
        FROM CodeFirstDatabase.NewsSite AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for MobilniPortalNovicContext12.Feeds
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("MobilniPortalNovicContext12.Feeds", @"
    SELECT VALUE -- Constructing Feeds
        [MobilniPortalNovicLib.Models.Feed](T1.Feed_FeedId, T1.Feed_url, T1.Feed_CategoryId, T1.Feed_NewsSiteId, T1.Feed_LastUpdated)
    FROM (
        SELECT 
            T.FeedId AS Feed_FeedId, 
            T.url AS Feed_url, 
            T.CategoryId AS Feed_CategoryId, 
            T.NewsSiteId AS Feed_NewsSiteId, 
            T.LastUpdated AS Feed_LastUpdated, 
            True AS _from0
        FROM CodeFirstDatabase.Feed AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for MobilniPortalNovicContext12.Categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("MobilniPortalNovicContext12.Categories", @"
    SELECT VALUE -- Constructing Categories
        [MobilniPortalNovicLib.Models.Category](T1.Category_CategoryId, T1.Category_Name)
    FROM (
        SELECT 
            T.CategoryId AS Category_CategoryId, 
            T.Name AS Category_Name, 
            True AS _from0
        FROM CodeFirstDatabase.Category AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for MobilniPortalNovicContext12.NewsFiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("MobilniPortalNovicContext12.NewsFiles", @"
    SELECT VALUE -- Constructing NewsFiles
        [MobilniPortalNovicLib.Models.NewsFile](T1.NewsFile_NewsId, T1.NewsFile_ShortContent, T1.NewsFile_Title, T1.NewsFile_Content, T1.NewsFile_PubDate, T1.NewsFile_FeedId)
    FROM (
        SELECT 
            T.NewsId AS NewsFile_NewsId, 
            T.ShortContent AS NewsFile_ShortContent, 
            T.Title AS NewsFile_Title, 
            T.Content AS NewsFile_Content, 
            T.PubDate AS NewsFile_PubDate, 
            T.FeedId AS NewsFile_FeedId, 
            True AS _from0
        FROM CodeFirstDatabase.NewsFile AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for MobilniPortalNovicContext12.Clicks
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("MobilniPortalNovicContext12.Clicks", @"
    SELECT VALUE -- Constructing Clicks
        [MobilniPortalNovicLib.Models.ClickCounter](T1.ClickCounter_ClickId, T1.ClickCounter_ClickDate, T1.ClickCounter_Location, T1.ClickCounter_NewsId, T1.ClickCounter_UserId)
    FROM (
        SELECT 
            T.ClickId AS ClickCounter_ClickId, 
            T.ClickDate AS ClickCounter_ClickDate, 
            T.Location AS ClickCounter_Location, 
            T.NewsId AS ClickCounter_NewsId, 
            T.UserId AS ClickCounter_UserId, 
            True AS _from0
        FROM CodeFirstDatabase.ClickCounter AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for MobilniPortalNovicContext12.Users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("MobilniPortalNovicContext12.Users", @"
    SELECT VALUE -- Constructing Users
        [MobilniPortalNovicLib.Models.User](T1.User_UserId, T1.User_Username)
    FROM (
        SELECT 
            T.UserId AS User_UserId, 
            T.Username AS User_Username, 
            True AS _from0
        FROM CodeFirstDatabase.User AS T
    ) AS T1");
        }
    }
}
