//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_Categories_Categories_ParentCategoryId", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MobilniPortalNovicLib.Categories), "Categories1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.Categories), true)]
[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_Categories_CategoryId", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobilniPortalNovicLib.Categories), "ClickCounters", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.ClickCounters), true)]
[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_NewsFiles_Categories_CategoryId", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobilniPortalNovicLib.Categories), "NewsFiles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.NewsFiles), true)]
[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_NewsFiles_NewsId", "NewsFiles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobilniPortalNovicLib.NewsFiles), "ClickCounters", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.ClickCounters), true)]
[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_Users_UserId", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobilniPortalNovicLib.Users), "ClickCounters", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.ClickCounters), true)]
[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_Feeds_NewsSites_NewsSiteId", "NewsSites", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobilniPortalNovicLib.NewsSites), "Feeds", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.Feeds), true)]
[assembly: EdmRelationshipAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_NewsFiles_Feeds_FeedId", "Feeds", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobilniPortalNovicLib.Feeds), "NewsFiles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobilniPortalNovicLib.NewsFiles), true)]

#endregion

namespace MobilniPortalNovicLib
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db85cb6b1a69a1400b9dc5a06100d90696Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db85cb6b1a69a1400b9dc5a06100d90696Entities object using the connection string found in the 'db85cb6b1a69a1400b9dc5a06100d90696Entities' section of the application configuration file.
        /// </summary>
        public db85cb6b1a69a1400b9dc5a06100d90696Entities() : base("name=db85cb6b1a69a1400b9dc5a06100d90696Entities", "db85cb6b1a69a1400b9dc5a06100d90696Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db85cb6b1a69a1400b9dc5a06100d90696Entities object.
        /// </summary>
        public db85cb6b1a69a1400b9dc5a06100d90696Entities(string connectionString) : base(connectionString, "db85cb6b1a69a1400b9dc5a06100d90696Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db85cb6b1a69a1400b9dc5a06100d90696Entities object.
        /// </summary>
        public db85cb6b1a69a1400b9dc5a06100d90696Entities(EntityConnection connection) : base(connection, "db85cb6b1a69a1400b9dc5a06100d90696Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categories> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Categories>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Categories> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClickCounters> ClickCounters
        {
            get
            {
                if ((_ClickCounters == null))
                {
                    _ClickCounters = base.CreateObjectSet<ClickCounters>("ClickCounters");
                }
                return _ClickCounters;
            }
        }
        private ObjectSet<ClickCounters> _ClickCounters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Feeds> Feeds
        {
            get
            {
                if ((_Feeds == null))
                {
                    _Feeds = base.CreateObjectSet<Feeds>("Feeds");
                }
                return _Feeds;
            }
        }
        private ObjectSet<Feeds> _Feeds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewsFiles> NewsFiles
        {
            get
            {
                if ((_NewsFiles == null))
                {
                    _NewsFiles = base.CreateObjectSet<NewsFiles>("NewsFiles");
                }
                return _NewsFiles;
            }
        }
        private ObjectSet<NewsFiles> _NewsFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewsSites> NewsSites
        {
            get
            {
                if ((_NewsSites == null))
                {
                    _NewsSites = base.CreateObjectSet<NewsSites>("NewsSites");
                }
                return _NewsSites;
            }
        }
        private ObjectSet<NewsSites> _NewsSites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Categories categories)
        {
            base.AddObject("Categories", categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClickCounters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClickCounters(ClickCounters clickCounters)
        {
            base.AddObject("ClickCounters", clickCounters);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Feeds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeeds(Feeds feeds)
        {
            base.AddObject("Feeds", feeds);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewsFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewsFiles(NewsFiles newsFiles)
        {
            base.AddObject("NewsFiles", newsFiles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewsSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewsSites(NewsSites newsSites)
        {
            base.AddObject("NewsSites", newsSites);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db85cb6b1a69a1400b9dc5a06100d90696Model", Name="Categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categories object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        public static Categories CreateCategories(global::System.Int32 categoryId)
        {
            Categories categories = new Categories();
            categories.CategoryId = categoryId;
            return categories;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentCategoryId
        {
            get
            {
                return _ParentCategoryId;
            }
            set
            {
                OnParentCategoryIdChanging(value);
                ReportPropertyChanging("ParentCategoryId");
                _ParentCategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentCategoryId");
                OnParentCategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentCategoryId;
        partial void OnParentCategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentCategoryIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_Categories_Categories_ParentCategoryId", "Categories1")]
        public EntityCollection<Categories> Categories1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Categories_Categories_ParentCategoryId", "Categories1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Categories_Categories_ParentCategoryId", "Categories1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_Categories_Categories_ParentCategoryId", "Categories")]
        public Categories Categories2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Categories_Categories_ParentCategoryId", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Categories_Categories_ParentCategoryId", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categories> Categories2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Categories_Categories_ParentCategoryId", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Categories_Categories_ParentCategoryId", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_Categories_CategoryId", "ClickCounters")]
        public EntityCollection<ClickCounters> ClickCounters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClickCounters>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Categories_CategoryId", "ClickCounters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClickCounters>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Categories_CategoryId", "ClickCounters", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_NewsFiles_Categories_CategoryId", "NewsFiles")]
        public EntityCollection<NewsFiles> NewsFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Categories_CategoryId", "NewsFiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Categories_CategoryId", "NewsFiles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db85cb6b1a69a1400b9dc5a06100d90696Model", Name="ClickCounters")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClickCounters : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClickCounters object.
        /// </summary>
        /// <param name="clickId">Initial value of the ClickId property.</param>
        /// <param name="clickDate">Initial value of the ClickDate property.</param>
        /// <param name="newsId">Initial value of the NewsId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="dayOfWeek">Initial value of the DayOfWeek property.</param>
        /// <param name="timeOfDay">Initial value of the TimeOfDay property.</param>
        public static ClickCounters CreateClickCounters(global::System.Int32 clickId, global::System.DateTime clickDate, global::System.Int32 newsId, global::System.Int32 userId, global::System.Int32 categoryId, global::System.Int32 dayOfWeek, global::System.Int32 timeOfDay)
        {
            ClickCounters clickCounters = new ClickCounters();
            clickCounters.ClickId = clickId;
            clickCounters.ClickDate = clickDate;
            clickCounters.NewsId = newsId;
            clickCounters.UserId = userId;
            clickCounters.CategoryId = categoryId;
            clickCounters.DayOfWeek = dayOfWeek;
            clickCounters.TimeOfDay = timeOfDay;
            return clickCounters;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClickId
        {
            get
            {
                return _ClickId;
            }
            set
            {
                if (_ClickId != value)
                {
                    OnClickIdChanging(value);
                    ReportPropertyChanging("ClickId");
                    _ClickId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClickId");
                    OnClickIdChanged();
                }
            }
        }
        private global::System.Int32 _ClickId;
        partial void OnClickIdChanging(global::System.Int32 value);
        partial void OnClickIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ClickDate
        {
            get
            {
                return _ClickDate;
            }
            set
            {
                OnClickDateChanging(value);
                ReportPropertyChanging("ClickDate");
                _ClickDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClickDate");
                OnClickDateChanged();
            }
        }
        private global::System.DateTime _ClickDate;
        partial void OnClickDateChanging(global::System.DateTime value);
        partial void OnClickDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NewsId
        {
            get
            {
                return _NewsId;
            }
            set
            {
                OnNewsIdChanging(value);
                ReportPropertyChanging("NewsId");
                _NewsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsId");
                OnNewsIdChanged();
            }
        }
        private global::System.Int32 _NewsId;
        partial void OnNewsIdChanging(global::System.Int32 value);
        partial void OnNewsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DayOfWeek
        {
            get
            {
                return _DayOfWeek;
            }
            set
            {
                OnDayOfWeekChanging(value);
                ReportPropertyChanging("DayOfWeek");
                _DayOfWeek = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayOfWeek");
                OnDayOfWeekChanged();
            }
        }
        private global::System.Int32 _DayOfWeek;
        partial void OnDayOfWeekChanging(global::System.Int32 value);
        partial void OnDayOfWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeOfDay
        {
            get
            {
                return _TimeOfDay;
            }
            set
            {
                OnTimeOfDayChanging(value);
                ReportPropertyChanging("TimeOfDay");
                _TimeOfDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeOfDay");
                OnTimeOfDayChanged();
            }
        }
        private global::System.Int32 _TimeOfDay;
        partial void OnTimeOfDayChanging(global::System.Int32 value);
        partial void OnTimeOfDayChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_Categories_CategoryId", "Categories")]
        public Categories Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Categories_CategoryId", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Categories_CategoryId", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categories> CategoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Categories_CategoryId", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Categories_CategoryId", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_NewsFiles_NewsId", "NewsFiles")]
        public NewsFiles NewsFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_NewsFiles_NewsId", "NewsFiles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_NewsFiles_NewsId", "NewsFiles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NewsFiles> NewsFilesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_NewsFiles_NewsId", "NewsFiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_NewsFiles_NewsId", "NewsFiles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_Users_UserId", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Users_UserId", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Users_UserId", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Users_UserId", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Users_UserId", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db85cb6b1a69a1400b9dc5a06100d90696Model", Name="Feeds")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feeds : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Feeds object.
        /// </summary>
        /// <param name="feedId">Initial value of the FeedId property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="newsSiteId">Initial value of the NewsSiteId property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static Feeds CreateFeeds(global::System.Int32 feedId, global::System.String url, global::System.Int32 newsSiteId, global::System.DateTime lastUpdated)
        {
            Feeds feeds = new Feeds();
            feeds.FeedId = feedId;
            feeds.url = url;
            feeds.NewsSiteId = newsSiteId;
            feeds.LastUpdated = lastUpdated;
            return feeds;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeedId
        {
            get
            {
                return _FeedId;
            }
            set
            {
                if (_FeedId != value)
                {
                    OnFeedIdChanging(value);
                    ReportPropertyChanging("FeedId");
                    _FeedId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeedId");
                    OnFeedIdChanged();
                }
            }
        }
        private global::System.Int32 _FeedId;
        partial void OnFeedIdChanging(global::System.Int32 value);
        partial void OnFeedIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NewsSiteId
        {
            get
            {
                return _NewsSiteId;
            }
            set
            {
                OnNewsSiteIdChanging(value);
                ReportPropertyChanging("NewsSiteId");
                _NewsSiteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsSiteId");
                OnNewsSiteIdChanged();
            }
        }
        private global::System.Int32 _NewsSiteId;
        partial void OnNewsSiteIdChanging(global::System.Int32 value);
        partial void OnNewsSiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FeedName
        {
            get
            {
                return _FeedName;
            }
            set
            {
                OnFeedNameChanging(value);
                ReportPropertyChanging("FeedName");
                _FeedName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FeedName");
                OnFeedNameChanged();
            }
        }
        private global::System.String _FeedName;
        partial void OnFeedNameChanging(global::System.String value);
        partial void OnFeedNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_Feeds_NewsSites_NewsSiteId", "NewsSites")]
        public NewsSites NewsSites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsSites>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Feeds_NewsSites_NewsSiteId", "NewsSites").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsSites>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Feeds_NewsSites_NewsSiteId", "NewsSites").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NewsSites> NewsSitesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsSites>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Feeds_NewsSites_NewsSiteId", "NewsSites");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NewsSites>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Feeds_NewsSites_NewsSiteId", "NewsSites", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_NewsFiles_Feeds_FeedId", "NewsFiles")]
        public EntityCollection<NewsFiles> NewsFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Feeds_FeedId", "NewsFiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NewsFiles>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Feeds_FeedId", "NewsFiles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db85cb6b1a69a1400b9dc5a06100d90696Model", Name="NewsFiles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewsFiles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewsFiles object.
        /// </summary>
        /// <param name="newsId">Initial value of the NewsId property.</param>
        /// <param name="shortContent">Initial value of the ShortContent property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="feedId">Initial value of the FeedId property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        public static NewsFiles CreateNewsFiles(global::System.Int32 newsId, global::System.String shortContent, global::System.String title, global::System.String content, global::System.DateTime pubDate, global::System.Int32 feedId, global::System.Int32 categoryId, global::System.String link)
        {
            NewsFiles newsFiles = new NewsFiles();
            newsFiles.NewsId = newsId;
            newsFiles.ShortContent = shortContent;
            newsFiles.Title = title;
            newsFiles.Content = content;
            newsFiles.PubDate = pubDate;
            newsFiles.FeedId = feedId;
            newsFiles.CategoryId = categoryId;
            newsFiles.Link = link;
            return newsFiles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NewsId
        {
            get
            {
                return _NewsId;
            }
            set
            {
                if (_NewsId != value)
                {
                    OnNewsIdChanging(value);
                    ReportPropertyChanging("NewsId");
                    _NewsId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NewsId");
                    OnNewsIdChanged();
                }
            }
        }
        private global::System.Int32 _NewsId;
        partial void OnNewsIdChanging(global::System.Int32 value);
        partial void OnNewsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShortContent
        {
            get
            {
                return _ShortContent;
            }
            set
            {
                OnShortContentChanging(value);
                ReportPropertyChanging("ShortContent");
                _ShortContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShortContent");
                OnShortContentChanged();
            }
        }
        private global::System.String _ShortContent;
        partial void OnShortContentChanging(global::System.String value);
        partial void OnShortContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PubDate
        {
            get
            {
                return _PubDate;
            }
            set
            {
                OnPubDateChanging(value);
                ReportPropertyChanging("PubDate");
                _PubDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PubDate");
                OnPubDateChanged();
            }
        }
        private global::System.DateTime _PubDate;
        partial void OnPubDateChanging(global::System.DateTime value);
        partial void OnPubDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeedId
        {
            get
            {
                return _FeedId;
            }
            set
            {
                OnFeedIdChanging(value);
                ReportPropertyChanging("FeedId");
                _FeedId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeedId");
                OnFeedIdChanged();
            }
        }
        private global::System.Int32 _FeedId;
        partial void OnFeedIdChanging(global::System.Int32 value);
        partial void OnFeedIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_NewsFiles_Categories_CategoryId", "Categories")]
        public Categories Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Categories_CategoryId", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Categories_CategoryId", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categories> CategoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Categories_CategoryId", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categories>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Categories_CategoryId", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_NewsFiles_NewsId", "ClickCounters")]
        public EntityCollection<ClickCounters> ClickCounters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClickCounters>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_NewsFiles_NewsId", "ClickCounters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClickCounters>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_NewsFiles_NewsId", "ClickCounters", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_NewsFiles_Feeds_FeedId", "Feeds")]
        public Feeds Feeds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Feeds>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Feeds_FeedId", "Feeds").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Feeds>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Feeds_FeedId", "Feeds").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Feeds> FeedsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Feeds>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Feeds_FeedId", "Feeds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Feeds>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_NewsFiles_Feeds_FeedId", "Feeds", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db85cb6b1a69a1400b9dc5a06100d90696Model", Name="NewsSites")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewsSites : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewsSites object.
        /// </summary>
        /// <param name="siteId">Initial value of the SiteId property.</param>
        public static NewsSites CreateNewsSites(global::System.Int32 siteId)
        {
            NewsSites newsSites = new NewsSites();
            newsSites.SiteId = siteId;
            return newsSites;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteId
        {
            get
            {
                return _SiteId;
            }
            set
            {
                if (_SiteId != value)
                {
                    OnSiteIdChanging(value);
                    ReportPropertyChanging("SiteId");
                    _SiteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteId");
                    OnSiteIdChanged();
                }
            }
        }
        private global::System.Int32 _SiteId;
        partial void OnSiteIdChanging(global::System.Int32 value);
        partial void OnSiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_Feeds_NewsSites_NewsSiteId", "Feeds")]
        public EntityCollection<Feeds> Feeds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Feeds>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Feeds_NewsSites_NewsSiteId", "Feeds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Feeds>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_Feeds_NewsSites_NewsSiteId", "Feeds", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db85cb6b1a69a1400b9dc5a06100d90696Model", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        public static Users CreateUsers(global::System.Int32 userId, global::System.String username)
        {
            Users users = new Users();
            users.UserId = userId;
            users.Username = username;
            return users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db85cb6b1a69a1400b9dc5a06100d90696Model", "FK_ClickCounters_Users_UserId", "ClickCounters")]
        public EntityCollection<ClickCounters> ClickCounters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClickCounters>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Users_UserId", "ClickCounters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClickCounters>("db85cb6b1a69a1400b9dc5a06100d90696Model.FK_ClickCounters_Users_UserId", "ClickCounters", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
